"""
HTML Renderer - Creates beautiful email-ready newsletter
"""
from datetime import datetime
import json

class HTMLRenderer:
    """Converts newsletter to HTML email format"""
    
    def create_html(self, newsletter_data, output_path=None):
        """Generate HTML from newsletter data"""
        
        if output_path is None:
            output_path = f"output/newsletter_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        # Build HTML sections (ONCE per section)
        sections_html = ""
        for section in newsletter_data.get('sections', []):
            # Check if section has an image (now smaller)
            image_html = ""
            if 'image' in section and section['image']:
                image_html = f"""
                <div style="text-align: center; margin: 15px 0;">
                    <img src="{section['image']['url']}" 
                         alt="{section['image'].get('alt_text', 'Newsletter image')}"
                         style="max-width: 100%; width: 100%; max-height: 200px; object-fit: cover; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
                    <p style="font-size: 10px; color: #999; margin-top: 5px;">{section['image'].get('attribution', 'Image')}</p>
                </div>
                """
            
            # Build article links section
            article_links_html = ""
            if 'article_links' in section and section['article_links']:
                article_links_html = '<div style="margin-top: 15px; padding: 10px; background-color: #f0f7ff; border-radius: 5px;">'
                article_links_html += '<p style="font-size: 13px; font-weight: bold; margin-bottom: 8px;">📚 Source Articles:</p><ul style="margin: 0; padding-left: 20px;">'
                for link in section['article_links'][:3]:  # Max 3 links per section
                    article_links_html += f'<li style="margin: 5px 0; font-size: 12px;"><a href="{link["url"]}" target="_blank" style="color: #3498db; text-decoration: none;">{link["title"][:80]}</a>'
                    if link.get('summary'):
                        article_links_html += f'<br><span style="font-size: 11px; color: #666;">{link["summary"]}</span>'
                    article_links_html += '</li>'
                article_links_html += '</ul></div>'
            
            # Build the section (ONCE)
            sections_html += f"""
            <div style="margin-bottom: 30px; padding: 15px; background-color: #f9f9f9; border-radius: 8px;">
                <h2 style="color: #2c3e50; border-left: 4px solid #3498db; padding-left: 15px;">{section['header']}</h2>
                {image_html}
                <p style="font-size: 16px; line-height: 1.6; color: #34495e;">{section['intro']}</p>
                <ul style="list-style-type: none; padding-left: 0;">
            """
            for bullet in section.get('bullets', []):
                sections_html += f'<li style="margin: 10px 0; padding-left: 20px;">✓ {bullet}</li>\n'
            
            sections_html += f"""
                </ul>
                {article_links_html}
            </div>
            """
        
        # Complete HTML template
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Weekly Pulse Newsletter</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }}
        .container {{
            background-color: white;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            padding-bottom: 20px;
            border-bottom: 3px solid #3498db;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #2c3e50;
            margin-bottom: 5px;
        }}
        .header p {{
            color: #7f8c8d;
            font-size: 14px;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📬 Weekly Pulse</h1>
            <p>Your AI-curated newsletter for the week of {datetime.now().strftime('%B %d, %Y')}</p>
        </div>
        
        {sections_html}
        
        <div class="footer">
            <p>Generated by Weekly Pulse AI System • Stay curious, stay informed</p>
            <p><small>This is an automated newsletter created from publicly available sources.</small></p>
        </div>
    </div>
</body>
</html>
"""
        
        # Save HTML file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"✓ HTML newsletter saved to: {output_path}")
        return output_path

# Quick integration with orchestrator
if __name__ == "__main__":
    # Test with sample data
    test_newsletter = {
        'sections': [
            {'header': 'AI Breakthroughs', 'intro': 'This week in AI...', 'bullets': ['News 1', 'News 2']}
        ]
    }
    renderer = HTMLRenderer()
    renderer.create_html(test_newsletter)